### ISSUE TITLE
Пора апгрейдить на Webpack 4 + Angular 6

### ISSUE THREAD

**Issue by antonpegov** [Angular-RU/webpack-angular-starter#1]
Я на последнем пректе использовал этот стартер, но хотелось бы его ещё больше упростить: https://github.com/antonpegov/angular-webpack-starter/tree/minimal
Еще тесты не смог на нём запустить.

**Comment by antonpegov** [comment]
Я на последнем пректе использовал этот стартер, но хотелось бы его ещё больше упростить: https://github.com/antonpegov/angular-webpack-starter/tree/minimal

**Comment by splincode** [comment]
Will not fixed
https://github.com/gdi2290/angular-starter
